apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demohelloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demohelloworld
    spec:
      containers:
      - name: demohelloworld
        image: acrcb.azurecr.io/demohelloworld:#{Build.BuildId}#
        ports:
        - containerPort: 3000
          name: demohelloworld
---
apiVersion: v1
kind: Service
metadata:
  name: demohelloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demohelloworld

    # image: acrcb.azurecr.io/demo1:#{Build.BuildId}#