apiVersion: v1
kind: Deployment
metadata:
  name: demo1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: acrcb.azurecr.io/demo1:#{Build.BuildId}#
        ports:
        - containerPort: 3000
          name: demo3
---
apiVersion: v1
kind: Service
metadata:
  name: demo1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demo1

    # image: acrcb.azurecr.io/demo1:#{Build.BuildId}#