apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbreakspear/demohelloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbreakspear/demohelloworld
    spec:
      containers:
      - name: cbreakspear/demohelloworld
        image: acrcb.azurecr.io/cbreakspear/demohelloworld:#{Build.BuildId}#
        ports:
        - containerPort: 3000
          name: cbreakspear/demohelloworld
---
apiVersion: v1
kind: Service
metadata:
  name: cbreakspear/demohelloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: cbreakspear/demohelloworld

    # image: acrcb.azurecr.io/demo1:#{Build.BuildId}#