apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo3
    spec:
      containers:
      - name: demo3
        image: acrcb.azurecr.io/demo3:#{Build.BuildId}#
        ports:
        - containerPort: 3000
          name: demo3
---
apiVersion: v1
kind: Service
metadata:
  name: demo3
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demo3

    # image: acrcb.azurecr.io/demo1:#{Build.BuildId}#